version: 2
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/user-data-for-fraud-prevention

    steps:
      - checkout

      - run: npm install
      
      # run build
      - run : npm run build

      # run tests and generate coverage 
      - run : 
          name : "Run tests and generate coverage report"
          command : npm run test:coverage
      
      - store_artifacts:
          path: coverage
          
      - run : auto shipit

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}

workflows:
  version: 2
  build:
    jobs:
      - build
