version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/user-data-for-fraud-prevention

    steps:
      - checkout

      - run: npm install
      
      # run build
      - run : npm run build

      # run tests!
      - run: npm test

      # run canary
      - run: canary
workflows:
  version: 2
  build:
    jobs:
      - build